[book]
authors = ["mia entropy"]
language = "en"
multilingual = false
src = "src"
title = "Eberban Reference Grammar"

[output.html]
default-theme = "rust"
mathjax-support = true
git-repository-url = "https://github.com/eberban/eberban"
git-repository-icon = "fa-github"
curly-quotes = true
site-url = "https://eberban.github.io/eberban/books/refgram/book/"

additional-css = [
    "res/leipzig.min.css",
    "res/style.css",
]
additional-js = [
    "res/leipzig.min.js",
    "res/leipzig_apply.js",
]

[preprocessor.regex-replacer]
command="mdbook-regex-replacer"

[[preprocessor.regex-replacer.items]]
regex="```gloss\n(?P<content>(?s:.)*?)\n```"
rep="<div data-gloss>\n\n${content}\n</div>"

[[preprocessor.regex-replacer.items]]
regex="<spoiler>\n(?P<title>(?s:.)*?)\n-{2,}\n(?P<content>(?s:.)*?)\n</spoiler>"
rep="<details><summary>\n\n${title}\n</summary><div>\n\n${content}\n</div></details>"