name: Deploy GitHub Pages

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache mdbook binary
        id: cache-mdbook
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/mdbook
          key: ${{runner.os}}-mdbook

      - name: Install Rust (if no cache)
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdbook (if no cache)
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: cargo install --vers "^0.4.4" mdbook

      - name: Build book
        run: |
          ~/.cargo/bin/mdbook build books/tour
          rm -f books/tour/.gitignore
        
      - name: Commit changes to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build book from master
          branch: gh-pages
          file_pattern: books/tour/book/*
          push_options: '--force'
          skip_dirty_check: true
