name: Build & Preview/Deploy

on:
  push:
    branches: [master]
  
  pull_request:
    branches: [master]
  
  workflow_dispatch:

jobs:
  build-and-preview-or-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Rust binaries
        id: cache-rust
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/*
          # This key must be changed every time a new Rust binary is added.
          key: ${{runner.os}}-rust

      - name: Install mdbook
        run: |
          mkdir bins
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./bins
          echo `pwd`/bins >> $GITHUB_PATH
          
      - name: Install mdbook-linkcheck
        run: |
          cd ./bins
          curl -o ./linkcheck.zip -sSL https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.6/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
          unzip linkcheck.zip
          cd ..

      - name: Install mdbook-regex-replacer
        if: steps.cache-rust.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-regex-replacer
          version: latest
          use-tool-cache: true

      - name: Build refgram book
        run: |
          mdbook build books/refgram
        
      - name: Install NPM dependencies for the website
        run: |
          cd web
          npm install
          cd ..

      - name: Build the website
        run: |
          cd web
          npm run build-to-deploy
          cd ..

      - name: Remove extraneous files
        run: |
          rm -f .gitignore
          rm -f dictionary/package.json
          rm -rf web/
  
      - name: Deploy preview
        if: ${{ github.event.pull_request.base.ref == 'refs/heads/master' }}
        uses: rossjrw/pr-preview-action@v1

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          commit-message: Update GitHub pages
          folder: .
          branch: gh-pages
          clean: false
          force: false
