name: Deploy GitHub Pages

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Cache mdbook binary
      #   id: cache-mdbook
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cargo/bin/mdbook*
      #     key: ${{runner.os}}-rust

      # - name: Install Rust (if no cache)
      #   if: steps.cache-mdbook.outputs.cache-hit != 'true'
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true

      # - name: Install mdbook (if no cache)
      #   if: steps.cache-mdbook.outputs.cache-hit != 'true'
      #   run: cargo install --vers "^0.4.4" mdbook

      # - name: Install mdbook-linkcheck (if no cache)
      #   if: steps.cache-mdbook.outputs.cache-hit != 'true'
      #   run: cargo install mdbook-linkcheck

      - name: Install mdbook
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git rust-lang/mdBook

      - name: Install mdbook-linkcheck
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git Michael-F-Bryan/mdbook-linkcheck

      - name: Build reference book
        run: |
          ~/.cargo/bin/mdbook build books/reference_en

      - name: Build tour book
        run: |
          ~/.cargo/bin/mdbook build books/tour_en
        
      - name: Install NPM dependencies
        run: |
          cd node
          npm install
          cd ..

      - name: Build JS bundle
        run: |
          cd node
          npm run build
          cd ..

      - name: Commit changes to gh-pages
        run: |
          rm -f .gitignore
          echo "node_modules" > .gitignore
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b tmp/gh-pages
          git add -A
          git commit -m "Update GitHub pages"
          git push origin tmp/gh-pages:gh-pages --force
